# Generated by Django 3.2.9 on 2021-12-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccionenvio',
            old_name='nombre',
            new_name='ciudad',
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='codigopostal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='estado',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
